### ISSUE TITLE
Include BetterGPSLabels

### ISSUE THREAD

**Issue by hmatt1** [ski-freak/TrackmaniaItemsSorted#2]
Firstly, thanks for doing this! The organization is great.

I wanted to recommend including the GPS Labels item set. It is scenery, but I don't consider it to be track-specific and can be re-used on many tracks. Feel free to close this issue if you don't want to include it.

https://item.exchange/set/view/10883

**Comment by ski-freak** [comment]
Tbh I just don't like them lol, I can add them to the list of notable exclusions though.
